services:
  - type: web
    name: chat-flask-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 1 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
